version: '3'
services:          
    frontend:
        build: 
            context : .
            args:
                ENV: prod 

        container_name: frontend-prod
        ports:
            - "80:80"
            - "443:443"
